language: java
jdk:
  - oraclejdk8

# env:
#   - TRAVIS_NODE_VERSION="6.9.2"
#
sudo: true

addons:
  code_climate:
    repo_token: 8860173d24d4bee5353db985c3ef17bdfbf06ca038474f8b0b9f883410f32561

# before_install:
#   - cd src/main/app
#   # Repo for newer Node.js versions
#   - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
#   # Repo for Yarn
#   - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
#   - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
#   - sudo apt-get update -qq

# install:
#   - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
#   - sudo apt-get install -y -qq yarn
#   - yarn install
#
# before_script:
#   - yarn test -- --coverage
#   - cd ../../../

# script:
#   - mvn clean package

notifications:
  slack:
    rooms:
      - p632:20oR0X45QVtC9RACNHghchWR
    on_success: change
    on_failure: always

after_success:
   - yarn global add codeclimate-test-reporter
   - codeclimate-test-reporter < src/main/app/coverage/lcov.info
